source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

#pod 'TTTAttributedLabel', '1.10.1'
#pod 'SDCAlertView', '~> 2.4.1'
pod 'MBProgressHUD', '0.9'
pod 'Masonry', '~> 0.6.4'
#pod 'JSONKit', '~> 1.5pre'